// Note: real module directory UI — see .agents/notes/blueprint/module-responsibilities.md
import { expect, test, type Page } from '@playwright/test'
import { readCorpus } from '../helpers/note-corpus'

const card = (page: Page, title: string) => page.locator('.react-flow__node').filter({ has: page.locator('.bp-node-card__title', { hasText: new RegExp(`^${title}$`) }) })
const nav = (page: Page) => page.getByRole('navigation', { name: '模块导航' })
for (const surface of ['', '&workbench']) test(`real corpus module preview, immediate groups, lazy source and return ${surface}`, async ({ page }) => {
  test.setTimeout(60_000)
  const root = process.cwd(), corpus = await readCorpus(root)
  const { blueprint } = corpus
  await page.addInitScript(graph => { (window as any).noteCorpus = graph }, blueprint)
  await page.exposeFunction('readCorpusNote', (uri: string) => corpus.read(uri))
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/blueprint-architecture.html?corpus&cwd=' + encodeURIComponent(root) + surface)
  await expect(nav(page).locator('[aria-current="page"]')).toHaveText('JanusX')
  await card(page, 'Note 与蓝图').click()
  await expect(page.locator('.bp-node-detail')).toContainText('通过共享 Note 读取边界')
  await card(page, 'Note 与蓝图').dblclick()
  await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Note 与蓝图')
  await expect(card(page, 'Note 与蓝图')).toBeAttached()
  await expect(card(page, '模块投影与导航')).toBeAttached()
  await expect(card(page, '会话检查点')).toHaveCount(0)
  await page.getByRole('button', { name: '适应画布', exact: true }).first().click()
  await card(page, '模块投影与导航').dblclick()
  await expect(nav(page).locator('[aria-current="page"]')).toHaveText('模块投影与导航')
  await expect(card(page, '模块投影与导航')).toBeAttached()
  await expect(card(page, '蓝图统一浏览、模块预览与模块内导航')).toBeAttached()
  await page.evaluate(() => (window as any).architectureFixture.focus('蓝图统一浏览、模块预览与模块内导航'))
  await expect(page.locator('.bp-node-detail')).toContainText('AC-8')
  await expect(page.locator('.bp-node-detail')).toContainText('模块职责和目录')
  await page.screenshot({ path: test.info().outputPath('real-module-directory.png'), fullPage: true, animations: 'disabled' })
  await nav(page).getByRole('button', { name: '返回', exact: true }).click()
  await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Note 与蓝图')
  await expect(page.locator('.bp-node-detail__title')).toHaveText('模块投影与导航')
  await nav(page).getByRole('button', { name: '返回', exact: true }).click()
  await expect(nav(page).locator('[aria-current="page"]')).toHaveText('JanusX')
  await expect(page.locator('.bp-node-detail__title')).toHaveText('Note 与蓝图')
  expect(errors).toEqual([])
  expect(await page.evaluate(() => (window as any).workbenchFixture.saves)).toEqual([])
})
