import { expect, test, type Page } from '@playwright/test'

test.beforeEach(({ page }) => {
  page.on('pageerror', error => { throw error })
})

const panel = (page: Page) => page.getByTestId('blueprint-chat')
const actions = (page: Page) => panel(page).getByRole('region', { name: 'Blueprint changes' })
const approve = (page: Page) => panel(page).getByRole('button', { name: 'Approve and apply selected', exact: true })

async function discuss(page: Page, query = '') {
  await page.goto('/project.html' + query)
  await page.addStyleTag({ content: '[data-testid="main-chat"],[data-testid="task"]{display:none}.fixture-layout{padding:12px}.fixture-layout>section{display:flex;flex-direction:column;height:650px;max-width:440px;min-height:0}' })
  await panel(page).locator('textarea').fill('Clarify the Note title, preserving other content')
  await panel(page).locator('textarea').press('Enter')
  await expect(panel(page)).toContainText('Project reply in progress')
  await page.evaluate(() => (window as any).projectFixture.finishStream())
  await expect(actions(page).getByRole('button', { name: 'Compose as proposal', exact: true })).toBeEnabled()
}

async function propose(page: Page) {
  await actions(page).getByRole('button', { name: 'Compose as proposal', exact: true }).click()
  await expect(panel(page).locator('.bp-maintenance-approval')).toBeVisible()
}

test('discussion, partial approval, refreshed graph, audit and selected undo form one reachable flow', async ({ page }) => {
  await discuss(page)
  expect(await page.evaluate(() => (window as any).projectFixture.maintenance.starts.length)).toBe(0)
  await propose(page)
  const request = await page.evaluate(() => (window as any).projectFixture.streams.at(-1))
  expect(request.maintenanceTaskId).toBe('maintenance-1')
  expect(request.domain).toBe('project')
  expect(request.workspaceResources.map((item: any) => item.workspaceId)).toEqual(['ws'])
  await expect(approve(page)).toBeDisabled()
  await panel(page).getByRole('checkbox', { name: 'Select operation rename', exact: true }).check()
  await approve(page).click()
  await expect(panel(page).locator('.bp-maintenance-approval')).toHaveCount(0)
  const applied = await page.evaluate(() => (window as any).projectFixture.maintenance)
  expect(applied.applies[0].operationIds).toEqual(['rename'])
  expect(applied.mutations).toBe(1)
  expect(applied.refreshes).toContain('C:/fixture')
  await panel(page).getByRole('button', { name: 'Complete maintenance', exact: true }).click()
  await panel(page).locator('summary').filter({ hasText: 'Applied history' }).click()
  await panel(page).getByRole('button', { name: 'Undo this application', exact: true }).click()
  await panel(page).getByRole('checkbox', { name: 'Select operation undo-rename', exact: true }).check()
  await panel(page).getByRole('button', { name: 'Approve and apply undo', exact: true }).click()
  expect(await page.evaluate(() => (window as any).projectFixture.maintenance.mutations)).toBe(2)
  expect(await page.evaluate(() => (window as any).projectFixture.snapshot().graph.nodes['44444444-4444-4333-8333-444444444444'].title)).toBe('Task')
})

test('changed proposal contents clear old selection and deletes each require confirmation', async ({ page }) => {
  await discuss(page)
  await propose(page)
  await panel(page).getByRole('checkbox', { name: 'Select operation rename', exact: true }).check()
  await page.evaluate(() => (window as any).projectFixture.maintenance.replaceProposal())
  await expect(approve(page)).toBeDisabled()
  await expect(panel(page).getByRole('checkbox', { name: 'Select operation rename', exact: true })).not.toBeChecked()
  await panel(page).getByRole('checkbox', { name: 'Obsolete notes', exact: true }).check()
  const confirmations = panel(page).locator('.bp-maintenance-delete-confirm input')
  await expect(confirmations).toHaveCount(2)
  await confirmations.nth(0).check()
  await expect(approve(page)).toBeDisabled()
  await confirmations.nth(1).check()
  await approve(page).click()
  const input = await page.evaluate(() => (window as any).projectFixture.maintenance.applies[0])
  expect(input.operationIds).toEqual(['delete-a', 'delete-b'])
  expect(input.confirmedDeleteOperationIds).toEqual(['delete-a', 'delete-b'])
})

test('stale source refusal leaves bytes unchanged and allows a fresh task', async ({ page }) => {
  await discuss(page)
  await propose(page)
  await panel(page).getByRole('checkbox', { name: 'Select operation rename', exact: true }).check()
  await page.evaluate(() => (window as any).projectFixture.maintenance.changeSourceHash('f'.repeat(64)))
  await approve(page).click()
  await expect(actions(page).getByRole('alert')).toContainText('STALE_SOURCE_HASH')
  expect(await page.evaluate(() => (window as any).projectFixture.maintenance.mutations)).toBe(0)
  await expect(actions(page).getByRole('button', { name: 'Compose as proposal', exact: true })).toBeDisabled()
  await panel(page).getByRole('button', { name: 'Complete maintenance', exact: true }).click()
  await expect(actions(page).getByRole('button', { name: 'Compose as proposal', exact: true })).toBeEnabled()
})

test('closing the panel while task creation waits cannot launch a hidden proposal', async ({ page }) => {
  await discuss(page)
  await page.evaluate(() => { (window as any).projectFixture.maintenance.gateStart = true })
  await actions(page).getByRole('button', { name: 'Compose as proposal', exact: true }).click()
  await expect.poll(() => page.evaluate(() => (window as any).projectFixture.maintenance.starts.length)).toBe(1)
  await page.getByRole('button', { name: 'Toggle blueprint', exact: true }).click()
  await page.evaluate(() => (window as any).projectFixture.maintenance.finishStart())
  await expect.poll(() => page.evaluate(() => (window as any).projectFixture.maintenance.tasks[0].status)).toBe('cancelled')
  expect(await page.evaluate(() => (window as any).projectFixture.streams.length)).toBe(1)
})

test('maintain-node binds Note references and scope, and rejects the other checkout until switched', async ({ page }) => {
  await discuss(page, '?two-checkouts')
  const nodeId = '44444444-4444-4333-8333-444444444444'
  await page.evaluate(id => (window as any).projectFixture.selectMaintenanceNode(id), nodeId)
  await propose(page)
  const fixture = await page.evaluate(() => ({ start: (window as any).projectFixture.maintenance.starts[0], stream: (window as any).projectFixture.streams.at(-1) }))
  expect(fixture.start.nodeScope).toEqual({ type: 'node', nodeId })
  expect(fixture.stream.noteRefs[0]).toMatchObject({ checkoutPath: 'C:/fixture', expectedHash: 'a'.repeat(64) })
  await page.evaluate(id => (window as any).projectFixture.selectMaintenanceNode('checkout-b:' + id), nodeId)
  await expect(actions(page).getByRole('button', { name: 'Maintain in Checkout B', exact: true })).toBeVisible()
  await expect(panel(page).locator('.bp-maintenance-approval')).toHaveCount(0)
  expect(await page.evaluate(() => (window as any).projectFixture.maintenance.mutations)).toBe(0)
  await actions(page).getByRole('button', { name: 'Maintain in Checkout B', exact: true }).click()
  await expect(panel(page)).not.toContainText('Clarify the Note title')
  await panel(page).locator('textarea').fill('Maintain the second checkout only')
  await panel(page).locator('textarea').press('Enter')
  await expect(panel(page)).toContainText('Project reply in progress')
  await page.evaluate(() => (window as any).projectFixture.finishStream())
  await actions(page).getByRole('button', { name: 'Compose as proposal', exact: true }).click()
  await expect.poll(() => page.evaluate(() => (window as any).projectFixture.maintenance.starts.length)).toBe(2)
  const second = await page.evaluate(() => ({ start: (window as any).projectFixture.maintenance.starts[1], stream: (window as any).projectFixture.streams.at(-1) }))
  expect(second.start).toMatchObject({ workspacePath: 'C:/fixture-b', nodeScope: { type: 'node', nodeId } })
  expect(second.start.blueprintId).toContain(':checkout-b')
  expect(second.stream.workspaceResources.map((item: any) => item.workspaceId)).toEqual(['ws-b'])
  expect(second.stream.noteRefs[0]).toMatchObject({ checkoutPath: 'C:/fixture-b', expectedHash: 'd'.repeat(64) })
})

test('clearing the conversation during task creation cancels the new task', async ({ page }) => {
  await discuss(page)
  await page.evaluate(() => { (window as any).projectFixture.maintenance.gateStart = true })
  await actions(page).getByRole('button', { name: 'Compose as proposal', exact: true }).click()
  await expect.poll(() => page.evaluate(() => (window as any).projectFixture.maintenance.starts.length)).toBe(1)
  await panel(page).getByRole('button', { name: 'Clear', exact: true }).click()
  await page.evaluate(() => (window as any).projectFixture.maintenance.finishStart())
  await expect(actions(page).getByRole('alert')).toContainText('conversation has changed')
  expect(await page.evaluate(() => (window as any).projectFixture.maintenance.tasks[0].status)).toBe('cancelled')
  expect(await page.evaluate(() => (window as any).projectFixture.streams.length)).toBe(1)
})

test('a failed task-list read stays visible and refresh retries it', async ({ page }) => {
  await discuss(page)
  await page.getByRole('button', { name: 'Toggle blueprint', exact: true }).click()
  await page.evaluate(() => { (window as any).projectFixture.maintenance.failList = true })
  await page.getByRole('button', { name: 'Toggle blueprint', exact: true }).click()
  await expect(actions(page).getByRole('alert')).toContainText('Task list unavailable')
  await expect(actions(page).getByRole('button', { name: 'Compose as proposal', exact: true })).toBeDisabled()
  await page.evaluate(() => { (window as any).projectFixture.maintenance.failList = false })
  await actions(page).getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(actions(page).getByRole('button', { name: 'Compose as proposal', exact: true })).toBeEnabled()
})
