import { expect, test } from '@playwright/test'

for (const mode of ['', '?workbench']) test(`current structure and original-source details ${mode || 'embedded'}`, async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/blueprint-architecture.html' + mode)
  await expect(page.getByRole('group', { name: '蓝图视图', exact: true })).toHaveCount(1)
  const selectorHost = page.locator(mode ? '.blueprint-workbench-toolbar' : '.blueprint-canvas-main')
  await expect(selectorHost.getByRole('button', { name: '系统结构', exact: true })).toBeVisible()
  await expect(selectorHost.getByRole('button', { name: '全部 Note', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '系统结构', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.react-flow__node')).toHaveCount(3)
  await expect(page.locator('.bp-node-card__progress')).toHaveCount(0)
  await expect(page.locator('.react-flow__edge').filter({ hasText: 'read' })).toHaveCount(1)
  await expect.poll(() => page.locator(mode ? '.blueprint-workbench-shell' : 'main').evaluate(element => element.getAnimations({ subtree: true }).filter(animation => animation.effect?.getTiming().iterations !== Infinity && animation.playState === 'running').length)).toBe(0)
  const information = page.locator('.bp-architecture-overview details').filter({ has: page.locator('summary', { hasText: /^蓝图信息$/ }) })
  await expect(information).not.toHaveAttribute('open', '')
  await expect(information.locator('section')).not.toBeVisible()
  await information.locator('summary').click()
  await expect(information.locator('section')).toContainText('检出范围')
  await information.locator('summary').click()
  await expect.poll(() => page.locator('.react-flow').evaluate(canvas => {
    const viewport = canvas.getBoundingClientRect()
    return [...canvas.querySelectorAll('.bp-node-card')].every(card => {
      const bounds = card.getBoundingClientRect()
      return bounds.width > 20 && bounds.height > 20 && bounds.left >= viewport.left && bounds.right <= viewport.right && bounds.top >= viewport.top && bounds.bottom <= viewport.bottom
    })
  })).toBe(true)
  const positions = await page.locator('.react-flow__node').evaluateAll(nodes => nodes.map(node => (node as HTMLElement).style.transform))
  expect(new Set(positions).size).toBe(3)
  await page.screenshot({ path: test.info().outputPath('structure.png'), fullPage: true })
  if (mode) {
    await page.getByRole('button', { name: '恢复默认布局', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: '恢复', exact: true }).click()
    expect(await page.evaluate(() => (window as any).workbenchFixture.saves)).toEqual([])
  }
  const draggable = page.locator('.react-flow__node').filter({ hasText: 'Reader module' })
  const beforeDrag = await draggable.getAttribute('style')
  const bounds = (await draggable.boundingBox())!
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2)
  await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width / 2 + 18, bounds.y + bounds.height / 2 + 8, { steps: 5 }); await page.mouse.up()
  await expect(draggable).toHaveAttribute('style', beforeDrag!)
  expect(await page.evaluate(() => (window as any).workbenchFixture.saves)).toEqual([])
  await page.locator('.react-flow__node').filter({ hasText: 'Reader module' }).dblclick()
  const related = page.getByRole('region', { name: '决策与相关工作' })
  await expect(related.getByRole('button', { name: 'Storage decision' })).toBeVisible()
  await expect(related.locator('button:disabled')).toHaveCount(1)
  await related.getByRole('button', { name: 'Implement child task' }).click()
  await expect(page.locator('.bp-node-detail')).toContainText('Child Note body with independent acceptance evidence.')
  await page.getByRole('button', { name: '适应画布', exact: true }).first().click()
  await expect(page.locator('.react-flow__node')).toHaveCount(3)
  expect(await page.evaluate(() => (window as any).workbenchFixture.reads.at(-1).uri)).toContain('55555555-5555-4555-8555-555555555555')
  await page.getByRole('button', { name: '全部 Note', exact: true }).click()
  await expect(page.locator('.react-flow__node')).toHaveCount(5)
  if (!mode) await expect(page.locator('.bp-node-card__progress')).toHaveCount(5)
  const fullPositions = await page.locator('.react-flow__node').evaluateAll(nodes => nodes.map(node => (node as HTMLElement).style.transform))
  await page.getByRole('button', { name: '系统结构', exact: true }).click()
  await expect(page.locator('.react-flow__node')).toHaveCount(3)
  await page.evaluate(() => (window as any).architectureFixture.refresh())
  await expect(page.locator('.react-flow__node').filter({ hasText: 'Reader module refreshed' })).toBeVisible()
  await page.getByRole('button', { name: '全部 Note', exact: true }).click()
  await expect(page.locator('.react-flow__node')).toHaveCount(5)
  expect(await page.locator('.react-flow__node').evaluateAll(nodes => nodes.map(node => (node as HTMLElement).style.transform))).toEqual(fullPositions)
  expect(await page.evaluate(() => (window as any).workbenchFixture.saves)).toEqual([])
  await page.screenshot({ path: test.info().outputPath('architecture.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('source focus reveals hidden tasks and untagged repositories retain all Notes', async ({ page }) => {
  await page.goto('/blueprint-architecture.html?collapsed')
  await expect(page.locator('.react-flow__node')).toHaveCount(3)
  await page.evaluate(() => (window as any).architectureFixture.focusTask())
  await expect(page.getByRole('button', { name: '全部 Note', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.react-flow__node')).toHaveCount(5)
  await page.goto('/blueprint-architecture.html?untagged')
  await expect(page.locator('.react-flow__node')).toHaveCount(5)
  await expect(page.getByRole('button', { name: '系统结构', exact: true })).toBeDisabled()
})
