import { expect, test } from '@playwright/test'

for (const mode of ['', '?workbench']) test(`legacy module declarations retain source details and diagnostics ${mode}`, async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/blueprint-architecture.html' + mode)
  await expect(page.locator('.react-flow__node')).toHaveCount(3)
  await expect(page.locator('.react-flow__edge').filter({ hasText: 'read' })).toHaveCount(1)
  const navigation = page.getByRole('navigation', { name: '模块导航' })
  await expect(navigation.locator('[aria-current="page"]')).toHaveText('蓝图概览')
  await page.getByRole('button', { name: '进入模块 Workbench architecture', exact: true }).click()
  await expect(navigation.locator('[aria-current="page"]')).toHaveText('Workbench architecture')
  await expect(page.locator('.react-flow__node').filter({ hasText: 'Unresolved module' })).toHaveCount(0)
  await navigation.getByRole('button', { name: '返回', exact: true }).click()
  await expect(navigation.locator('[aria-current="page"]')).toHaveText('蓝图概览')
  await expect(navigation.getByRole('button', { name: '返回', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '适应画布', exact: true }).first().click()
  await expect(page.locator('.react-flow__node')).toHaveCount(3)
  await expect(page.getByRole('button', { name: /^(系统结构|全部 Note)$/ })).toHaveCount(0)
  await expect(page.locator('.bp-node-card__progress')).toHaveCount(0)
  await expect(page.locator('.react-flow__edge').filter({ hasText: 'read' })).toHaveCount(1)
  const information = page.locator('.bp-architecture-overview details').filter({ has: page.locator('summary', { hasText: /^蓝图信息$/ }) })
  await information.locator('summary').click()
  await expect(information).toContainText('检出范围')
  await information.locator('summary').click()
  await page.locator('.react-flow__node').filter({ hasText: 'Reader module' }).click()
  await page.locator('.bp-browser-related > summary').click()
  const related = page.getByRole('region', { name: '决策与相关工作' })
  await expect(related.getByRole('button', { name: 'Storage decision' })).toBeVisible()
  await expect(related.locator('button:disabled')).toHaveCount(1)
  await related.getByRole('button', { name: 'Implement child task' }).click()
  await expect(page.locator('.bp-node-detail')).toContainText('Child Note body with independent acceptance evidence.')
  await expect(page.getByRole('navigation').locator('[aria-current="page"]')).toHaveText('Workbench architecture')
  await page.evaluate(() => (window as any).architectureFixture.refresh())
  await page.getByRole('button', { name: '适应画布', exact: true }).first().click()
  await expect(page.locator('.react-flow__node').filter({ hasText: 'Reader module refreshed' })).toBeVisible()
  expect(await page.evaluate(() => (window as any).workbenchFixture.saves)).toEqual([])
  expect(errors).toEqual([])
})

test('source focus and repositories without module declarations remain accessible', async ({ page }) => {
  await page.goto('/blueprint-architecture.html?collapsed')
  await expect(page.locator('.react-flow__node')).toHaveCount(3)
  await page.evaluate(() => (window as any).architectureFixture.focusTask())
  await expect(page.locator('.bp-node-detail')).toContainText('Child Note body with independent acceptance evidence.')
  await page.goto('/blueprint-architecture.html?untagged')
  await expect(page.locator('.react-flow__node')).toHaveCount(5)
  await expect(page.locator('.bp-browser-hint')).toContainText('尚无模块声明')
  await expect(page.getByRole('button', { name: /^(系统结构|全部 Note)$/ })).toHaveCount(0)
})
