import { expect, test, type Page } from '@playwright/test'

const card = (page: Page, title: string) => page.locator('.react-flow__node').filter({ has: page.locator('.bp-node-card__title', { hasText: new RegExp(`^${title}$`) }) })
const nav = (page: Page) => page.getByRole('navigation', { name: '模块导航' })
const fit = async (page: Page) => { await page.getByRole('button', { name: '适应画布', exact: true }).first().click() }

for (const surface of ['', '&workbench']) {
  test(`module preview, scoped pages, nested return and container design ${surface}`, async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await page.goto('/blueprint-architecture.html?v2' + surface)
    await expect(page.locator('.react-flow__node')).toHaveCount(4)
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Workbench architecture')
    await expect(nav(page).getByRole('button', { name: '蓝图概览', exact: true })).toHaveCount(0)
    await expect(nav(page).getByRole('button', { name: '返回', exact: true })).toBeDisabled()
    await card(page, 'Workbench architecture').click()
    await expect(page.locator('.bp-node-detail .bp-node-detail__title')).toHaveText('Workbench architecture')
    const homeLayout = await page.locator('.react-flow__node').evaluateAll(nodes => nodes.map(node => node.getAttribute('style')))
    await card(page, 'Workbench architecture').dblclick()
    await nav(page).getByRole('button', { name: 'Workbench architecture', exact: true }).click()
    expect(await page.locator('.react-flow__node').evaluateAll(nodes => nodes.map(node => node.getAttribute('style')))).toEqual(homeLayout)
    await expect(nav(page).getByRole('button', { name: '返回', exact: true })).toBeDisabled()
    await expect(page.getByRole('button', { name: /^(系统结构|全部 Note)$/ })).toHaveCount(0)
    await card(page, 'Reader module').click()
    await expect(page.locator('.bp-node-detail')).toContainText('Reader module responsibilities from module.md.')
    await expect(page.locator('.bp-node-detail .markdown-preview')).toBeInViewport()
    await expect(page.locator('.react-flow__node')).toHaveCount(4)
    await expect(page.locator('.bp-module-document-group')).toHaveCount(1)
    await expect(card(page, 'Root decision')).toBeVisible()
    const preview = (await page.locator('.bp-node-detail').boundingBox())!
    const canvas = (await page.locator('.react-flow').boundingBox())!
    expect(preview.x + preview.width).toBeLessThanOrEqual(canvas.x + 2)
    await card(page, 'Planned module').click()
    await expect(page.locator('.bp-node-detail')).toContainText('Planned module responsibilities from module.md.')
    await card(page, 'Reader module').click()
    const homeViewport = await page.locator('.react-flow__viewport').getAttribute('style')
    await card(page, 'Reader module').dblclick()
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Reader module')
    await fit(page)
    await expect(page.locator('.react-flow__node')).toHaveCount(7)
    await expect(card(page, 'Reader module')).toBeVisible()
    const rootBounds = (await card(page, 'Reader module').boundingBox())!
    const childBounds = (await card(page, 'Parser submodule').boundingBox())!
    expect(rootBounds.y + rootBounds.height).toBeLessThan(childBounds.y)
    await expect(card(page, 'Planned module')).toHaveCount(0)
    await expect(card(page, 'Root decision')).toHaveCount(0)
    await expect(card(page, 'Deep parsing document')).toHaveCount(0)
    await expect(page.locator('.bp-module-document-group')).toHaveCount(5)
    const frames = await page.locator('.bp-module-document-group').evaluateAll(elements => elements.map(element => ({ kind: element.getAttribute('data-kind'), owner: element.getAttribute('data-module-id'), border: getComputedStyle(element).borderStyle, bounds: element.getBoundingClientRect().toJSON() })))
    expect(frames.map(f => f.kind)).toEqual(['note', 'idea', 'requirement', 'decision', 'task'])
    expect(new Set(frames.map(f => f.owner)).size).toBe(1)
    expect(frames.every(f => f.border === 'dashed')).toBe(true)
    for (const kind of ['note', 'idea', 'requirement']) {
      const bounds = (await card(page, `Child ${kind}`).boundingBox())!, frame = frames.find(f => f.kind === kind)!.bounds
      expect(bounds.x).toBeGreaterThan(frame.x); expect(bounds.x + bounds.width).toBeLessThan(frame.x + frame.width)
      expect(bounds.y).toBeGreaterThan(frame.y); expect(bounds.y + bounds.height).toBeLessThan(frame.y + frame.height)
    }
    await expect(card(page, 'Parser submodule').locator('.bp-node-card--module')).toBeVisible()
    await expect(card(page, 'Child note').locator('.bp-node-card--document')).toBeVisible()
    const outlines = await page.locator('.bp-node-card--module').first().evaluate(el => ({ tab: getComputedStyle(el, '::before').content, border: getComputedStyle(el).borderTopWidth, radius: getComputedStyle(el).borderTopRightRadius }))
    expect(outlines.tab).toBe('""'); expect(outlines.border).toBe('2px'); expect(outlines.radius).toBe('10px')
    await page.screenshot({ path: test.info().outputPath('module-page-light.png'), fullPage: true })
    await page.evaluate(() => (window as any).architectureFixture.theme('dark'))
    await page.screenshot({ path: test.info().outputPath('module-page-dark.png'), fullPage: true })
    await card(page, 'Parser submodule').click()
    const readerViewport = await page.locator('.react-flow__viewport').getAttribute('style')
    await card(page, 'Parser submodule').dblclick()
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Parser submodule')
    await expect(card(page, 'Deep parsing document')).toBeVisible()
    await expect(page.locator('.react-flow__node')).toHaveCount(2)
    await expect(card(page, 'Parser submodule')).toBeVisible()
    await expect(card(page, 'Reader module')).toHaveCount(0)
    await card(page, 'Parser submodule').dblclick()
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Parser submodule')
    await nav(page).getByRole('button', { name: '返回', exact: true }).click()
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Reader module')
    await expect(page.locator('.bp-node-detail')).toContainText('Original Parser submodule content.')
    await expect(card(page, 'Parser submodule')).toHaveClass(/selected/)
    await expect(page.locator('.react-flow__viewport')).toHaveAttribute('style', readerViewport!)
    await nav(page).getByRole('button', { name: '返回', exact: true }).click()
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Workbench architecture')
    await expect(nav(page).getByRole('button', { name: '返回', exact: true })).toBeDisabled()
    await expect(page.locator('.bp-node-detail')).toContainText('Reader module responsibilities from module.md.')
    await expect(card(page, 'Reader module')).toHaveClass(/selected/)
    await expect(page.locator('.react-flow__viewport')).toHaveAttribute('style', homeViewport!)
    expect(await page.evaluate(() => (window as any).workbenchFixture.saves)).toEqual([])
    expect(errors).toEqual([])
  })

  test(`complete-source search, Chat and historical access ${surface}`, async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await page.goto('/blueprint-architecture.html?v2' + surface)
    await card(page, 'Planned module').getByRole('button', { name: '进入模块 Planned module' }).click()
    await expect(page.locator('.bp-browser-empty')).toBeVisible()
    await expect(page.locator('.react-flow__node')).toHaveCount(1)
    await expect(card(page, 'Planned module')).toBeVisible()
    const search = page.locator('.blueprint-toolbar__search').first()
    await search.fill('Deep parsing document')
    await page.getByRole('region', { name: '文档搜索结果' }).getByRole('button', { name: 'Deep parsing document' }).click()
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Parser submodule')
    await expect(page.locator('.bp-node-detail')).toContainText('Original Deep parsing document content.')
    await search.fill('')
    await page.evaluate(() => (window as any).architectureFixture.focus('Implement child task', 'explicit', 'Root decision'))
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Reader module')
    await expect(page.locator('.bp-node-detail')).toContainText('Child Note body with independent acceptance evidence.')
    await expect(card(page, 'Implement child task')).toHaveClass(/bp-assistant-target/)
    await page.evaluate(() => (window as any).architectureFixture.focus('Storage decision'))
    await expect(page.locator('.bp-node-detail .bp-node-detail__title')).toHaveText('Storage decision')
    await page.evaluate(() => (window as any).architectureFixture.focus('Root decision', 'none'))
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Reader module')
    await expect(page.locator('.bp-node-detail .bp-node-detail__title')).toHaveText('Storage decision')
    await page.evaluate(() => (window as any).architectureFixture.focus('Root decision'))
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Workbench architecture')
    await expect(page.locator('.bp-node-detail .bp-node-detail__title')).toHaveText('Root decision')
    await nav(page).getByRole('button', { name: '返回', exact: true }).click()
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Reader module')
    await page.evaluate(() => (window as any).architectureFixture.focus('Workbench architecture'))
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Workbench architecture')
    await expect(page.locator('.bp-node-detail .bp-node-detail__title')).toHaveText('Workbench architecture')
    await nav(page).getByRole('button', { name: 'Workbench architecture', exact: true }).click()
    await card(page, 'Planned module').dblclick()
    await expect(page.locator('.bp-browser-empty')).toBeVisible()
    await page.evaluate(() => (window as any).architectureFixture.focus('Deep parsing document'))
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Parser submodule')
    await expect(page.locator('.bp-node-detail')).toContainText('Original Deep parsing document content.')
    await page.locator('.bp-browser-unassigned summary').click()
    await page.locator('.bp-browser-unassigned').getByRole('button', { name: 'Legacy unassigned document' }).click()
    await expect(page.locator('.bp-node-detail')).toContainText('Original Legacy unassigned document content.')
    await page.locator('.bp-browser-unassigned').getByRole('button', { name: 'Retired module' }).click()
    await expect(page.locator('.bp-node-detail')).toContainText('Original Retired module content.')
    await page.locator('.bp-architecture-overview summary').filter({ hasText: /^蓝图信息$/ }).click()
    await expect(page.locator('.bp-architecture-overview')).toContainText('FIXTURE_PARSE_DIAGNOSTIC')
    expect(await page.evaluate(() => (window as any).workbenchFixture.saves)).toEqual([])
    expect(errors).toEqual([])
  })

  test(`single-root home starts with the module multi-row layout ${surface}`, async ({ page }) => {
    await page.goto('/blueprint-architecture.html?v2&wide' + surface)
    await expect(page.locator('.react-flow__node')).toHaveCount(6)
    await fit(page)
    await expect(card(page, 'Root decision').locator('.bp-node-card')).toHaveCSS('opacity', '1')
    await expect(card(page, 'Root decision')).toBeInViewport({ ratio: 0.999 })
    await expect(card(page, 'Workbench architecture')).toBeInViewport({ ratio: 0.999 })
    const rootBounds = (await card(page, 'Workbench architecture').boundingBox())!
    const first = (await card(page, 'Reader module').boundingBox())!
    const secondRow = (await card(page, 'Additional module B').boundingBox())!
    expect(rootBounds.y + rootBounds.height).toBeLessThan(first.y)
    expect(first.y + first.height).toBeLessThan(secondRow.y)
    expect(Math.abs(first.x - secondRow.x)).toBeLessThan(1)
    await expect(nav(page).locator('[aria-current="page"]')).toHaveText('Workbench architecture')
    await expect(nav(page).getByRole('button', { name: '返回', exact: true })).toBeDisabled()
    await page.screenshot({ path: test.info().outputPath('module-home-light.png'), fullPage: true, animations: 'disabled' })
    await page.evaluate(() => (window as any).architectureFixture.theme('dark'))
    await page.screenshot({ path: test.info().outputPath('module-home-dark.png'), fullPage: true, animations: 'disabled' })
  })
}
