import { expect, test } from '@playwright/test'

for (const surface of ['', '&workbench']) {
  test(`healthy module canvas shows sources only on demand ${surface}`, async ({ page }) => {
    await page.goto('/blueprint-architecture.html?v2&clean' + surface)
    const trigger = page.getByRole('button', { name: '数据来源', exact: true })
    await expect(trigger).toBeVisible()
    await expect(page.locator('.bp-source-attention')).toHaveCount(0)
    await expect(page.locator('.bp-architecture-overview, .bp-composition-overlay')).toHaveCount(0)
    const canvas = page.locator('.react-flow')
    await canvas.click({ position: { x: 10, y: 10 }, trial: true })
    const size = () => canvas.evaluate(el => ({ width: el.clientWidth, height: el.clientHeight }))
    const before = await size()
    await trigger.click()
    const dialog = page.getByRole('dialog', { name: '数据来源' })
    await expect(dialog).toBeVisible()
    await expect(dialog).toContainText('C:/architecture')
    await expect(dialog).toContainText('文档扫描完整')
    await expect(dialog).toContainText('没有额外的解析问题')
    await page.keyboard.press('Tab')
    expect(await page.evaluate(() => !!document.activeElement?.closest('.bp-source-dialog'))).toBe(true)
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(trigger).toBeFocused()
    if (surface) await expect(page.locator('.bp-maintenance-panel')).toBeVisible()
    // Compare layout sizes independently of the workbench's entrance scaling.
    expect(await size()).toEqual(before)
    await expect(page.getByRole('navigation', { name: '模块导航' }).locator('[aria-current="page"]')).toHaveText('Workbench architecture')
    await page.screenshot({ path: test.info().outputPath('sources-closed-light.png'), animations: 'disabled' })
    await trigger.click()
    await page.screenshot({ path: test.info().outputPath('sources-open-light.png'), animations: 'disabled' })
    await page.evaluate(() => (window as any).architectureFixture.theme('dark'))
    await page.screenshot({ path: test.info().outputPath('sources-open-dark.png'), animations: 'disabled' })
  })

  test(`diagnostics remain reachable without a persistent panel ${surface}`, async ({ page }) => {
    await page.goto('/blueprint-architecture.html?v2' + surface)
    const trigger = page.getByRole('button', { name: '数据来源 有待处理项', exact: true })
    await expect(trigger).toBeVisible()
    await trigger.click()
    const dialog = page.getByRole('dialog', { name: '数据来源' })
    await expect(dialog).toContainText('文档读取需要检查')
    await dialog.getByText('技术详情', { exact: true }).click()
    await expect(dialog).toContainText('FIXTURE_PARSE_DIAGNOSTIC')
    await dialog.getByRole('button', { name: '关闭', exact: true }).click()
    await page.locator('.react-flow__node').filter({ has: page.locator('.bp-node-card__title', { hasText: /^Reader module$/ }) }).click()
    await page.locator('.bp-browser-related > summary').click()
    await expect(page.locator('.bp-node-detail')).toContainText('模块接口 · 1')
    await expect(page.locator('.bp-node-detail')).not.toContainText('FIXTURE_PARSE_DIAGNOSTIC')
    await expect(page.locator('.bp-node-detail')).not.toContainText('组合蓝图')
    await page.locator('.bp-node-detail').getByRole('button', { name: '提供方：Workbench architecture' }).click()
    await expect(page.locator('.bp-node-detail__title')).toHaveText('Workbench architecture')
    expect(await page.evaluate(() => (window as any).workbenchFixture.saves)).toEqual([])
  })
}
