import { expect, test } from '@playwright/test'

test('composed graph exposes interfaces and selects the exact source checkout', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/blueprint-composition.html')
  await expect(page.locator('.react-flow__node')).toHaveCount(3)
  await expect(page.locator('.react-flow__minimap')).toBeVisible()
  await expect(page.locator('.react-flow__edge').filter({ hasText: 'reader' })).toBeVisible()
  await page.locator('.bp-composition-overlay summary').click()
  const panel = page.locator('.bp-composition-overlay')
  await expect(panel).toContainText('悬空需求')
  await expect(panel).toContainText('暂无消费者')
  await expect(panel).toContainText('未接入')
  await expect(panel).toContainText('来源已变化')
  await panel.getByRole('button', { name: '提供方：Provider checkout Y' }).click()
  await expect(page.locator('.bp-node-detail')).toContainText('Source from C:/dev-y')
  expect(await page.evaluate(() => (window as any).compositionFixture.reads.at(-1))).toContain('C:/dev-y|note://')
  await page.locator('.bp-node-detail .bp-panel-close').click()
  await page.locator('.react-flow__node').filter({ hasText: 'Provider checkout X' }).dblclick()
  await expect(page.locator('.bp-node-detail')).toContainText('Source from C:/dev-x')
  await page.screenshot({ path: test.info().outputPath('composition.png'), fullPage: true })
  expect(errors).toEqual([])
})
