import { expect, test } from '@playwright/test'

test('Note directory, source links, backlinks, code and context are reachable', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/note-wiki.html')
  await expect(page.getByText('Parent source content.')).toBeVisible()
  await page.locator('.markdown-preview').getByRole('button', { name: 'Child', exact: true }).click()
  await expect(page.getByText('Child source content.')).toBeVisible()
  await expect(page.locator('[data-note-anchor="goal"]')).toBeVisible()
  await page.getByRole('button', { name: 'src/wiki.ts' }).click()
  expect(await page.evaluate(() => (window as any).wikiFixture.openedFiles)).toEqual(['C:/fixture/wiki/src/wiki.ts'])
  await page.getByRole('tab', { name: '关系与反链' }).click()
  await expect(page.getByText('→ parent', { exact: true })).toBeVisible()
  await expect(page.getByText('← 引用本篇', { exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Knowledge wiki references' })).toBeVisible()
  await page.getByRole('tab', { name: '上下文' }).click()
  await expect(page.getByText('本篇、一跳邻居与祖先 · 2 篇')).toBeVisible()
  await page.getByText('Note 目录 · 2 篇', { exact: true }).click()
  await page.getByRole('textbox', { name: '查找 Note' }).fill('Parent')
  await page.getByRole('navigation', { name: 'Note 目录' }).getByRole('button', { name: 'Parent initiative' }).click()
  await expect(page.getByText('Parent source content.')).toBeVisible()
  await page.screenshot({ path: test.info().outputPath('note-wiki.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('late source responses do not overwrite current selection; failures retry and stale reads stay explicit', async ({ page }) => {
  await page.goto('/note-wiki.html')
  await expect(page.getByText('Parent source content.')).toBeVisible()
  await page.evaluate(() => { (window as any).wikiFixture.gated = true })
  await page.getByRole('button', { name: 'Select child' }).click()
  await expect.poll(() => page.evaluate(() => Boolean((window as any).wikiFixture.release))).toBe(true)
  await page.getByRole('button', { name: 'Select parent' }).click()
  await page.evaluate(() => (window as any).wikiFixture.release())
  await expect(page.getByText('Parent source content.')).toBeVisible()
  await expect(page.getByText('Child source content.')).toHaveCount(0)
  await page.evaluate(() => { (window as any).wikiFixture.failNext = true })
  await page.getByRole('button', { name: 'Select child' }).click()
  await expect(page.getByRole('alert')).toContainText('source unavailable')
  await page.getByRole('button', { name: '重试', exact: true }).click()
  await expect(page.getByText('Child source content.')).toBeVisible()
  await page.evaluate(() => { (window as any).wikiFixture.stale = true })
  await page.getByRole('button', { name: 'Select parent' }).click()
  await expect(page.getByText('源文已变化，当前显示新原文；关系仍来自旧快照。')).toBeVisible()
  await page.getByRole('button', { name: '刷新图谱' }).click()
  await expect(page.getByText('源文已变化，当前显示新原文；关系仍来自旧快照。')).toHaveCount(0)
})
