import { expect, test } from '@playwright/test'

const pageErrors: string[] = []
test.beforeEach(({ page }) => { pageErrors.length = 0; page.on('pageerror', (error) => pageErrors.push(error.message)) })
test.afterEach(() => expect(pageErrors).toEqual([]))

test('project entries share one stream, steering, questions and model across panel remounts', async ({ page }) => {
  await page.goto('/project.html')
  await page.addStyleTag({ content: '.fixture-layout { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:16px; padding:16px; } .fixture-layout > section { min-width:0; height:650px; overflow:auto; } .fixture-layout .janus-chat { width:100%; height:100%; } @media(max-width:600px) { .fixture-layout { grid-template-columns:minmax(0,1fr); } }' })
  const main = page.getByTestId('main-chat')
  const blueprint = page.getByTestId('blueprint-chat')
  await expect(blueprint.locator('.janus-chat')).toBeVisible()
  const id = await page.getByTestId('controller').getAttribute('data-id')
  await main.locator('textarea').fill('Inspect this task')
  await main.locator('textarea').press('Enter')
  await expect(blueprint).toContainText('Inspect this task')
  await expect(blueprint).toContainText('Project reply in progress')
  await blueprint.locator('.janus-chat textarea').fill('Keep the scope narrow')
  await blueprint.locator('.janus-chat textarea').press('Enter')
  await expect.poll(() => page.evaluate(() => (window as any).projectFixture.steers)).toBe(1)
  expect(await page.evaluate(() => (window as any).projectFixture.streams.length)).toBe(1)
  await page.getByRole('button', { name: 'Choose model B', exact: true }).click()
  await expect(page.getByTestId('controller')).toHaveAttribute('data-model', 'model-b')
  await page.getByRole('button', { name: 'Ask question', exact: true }).click()
  await expect(main).toContainText('Which scope?')
  await expect(blueprint).toContainText('Which scope?')
  await blueprint.getByRole('radio', { name: /Selected/ }).check()
  await blueprint.getByRole('button', { name: 'Answer', exact: true }).click()
  await expect(page.getByTestId('controller')).toHaveAttribute('data-questions', '0')
  await expect(main).not.toContainText('Which scope?')
  expect(await page.evaluate(() => (window as any).projectFixture.answers)).toBe(1)
  await page.getByRole('button', { name: 'Ask approval', exact: true }).click()
  await expect(main.locator('.janus-runtime-approval')).toBeVisible()
  await expect(blueprint.locator('.janus-runtime-approval')).toBeVisible()
  await blueprint.locator('.janus-runtime-approval-approve').click()
  await expect(main.locator('.janus-runtime-approval')).toHaveCount(0)
  await expect(blueprint.locator('.janus-runtime-approval')).toHaveCount(0)
  expect(await page.evaluate(() => (window as any).projectFixture.approvals)).toBe(1)
  await page.getByRole('button', { name: 'Toggle blueprint', exact: true }).click()
  expect(await page.evaluate(() => (window as any).projectFixture.aborts)).toBe(0)
  await page.getByRole('button', { name: 'Toggle blueprint', exact: true }).click()
  await expect(blueprint).toContainText('Keep the scope narrow')
  await expect(page.getByTestId('controller')).toHaveAttribute('data-id', id!)
  await page.getByRole('button', { name: 'New personal chat', exact: true }).click()
  await expect(page.getByTestId('controller')).not.toHaveAttribute('data-id', id!)
  await expect(page.getByTestId('project-controller')).toHaveAttribute('data-id', id!)
  await expect(page.getByTestId('project-controller')).toHaveAttribute('data-streaming', 'true')
  await expect(main).not.toContainText('Inspect this task')
  await expect(blueprint).toContainText('Inspect this task')
  await page.getByRole('button', { name: 'Return to project', exact: true }).click()
  await page.screenshot({ path: test.info().outputPath('shared-project-desktop.png'), fullPage: true, animations: 'disabled' })
  await blueprint.locator('.janus-chat-stop').click()
  await expect(page.getByTestId('controller')).toHaveAttribute('data-streaming', 'false')
  expect(await page.evaluate(() => (window as any).projectFixture.aborts)).toBe(1)
  await expect(main.locator('.janus-resource-chip')).toHaveCount(1)
  // The workspace-following dialog shows its target workspace inline.
  await expect(blueprint.locator('.bp-maintenance-context')).toContainText('Project')
  await expect(blueprint.locator('.bp-maintenance-controls')).toHaveCount(0)
  await expect(blueprint.getByRole('button', { name: 'Compose as proposal', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByTestId('controller')).toHaveAttribute('data-id', id!)
  await expect(page.getByTestId('main-chat')).toContainText('Inspect this task')
  await expect(page.getByTestId('main-chat').locator('.janus-resource-chip')).toHaveCount(1)
  await expect(page.getByTestId('blueprint-chat').locator('.bp-maintenance-context')).toContainText('Project')
})

test('task contract adoption enables preparation at a narrow viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/project.html')
  await page.addStyleTag({ content: '.fixture-layout { display:grid; grid-template-columns:minmax(0,1fr); gap:16px; padding:8px; } .fixture-layout > section { min-width:0; } [data-testid="main-chat"], [data-testid="blueprint-chat"] { display:none; }' })
  const task = page.getByTestId('task')
  await expect(task.getByRole('button', { name: 'Prepare run', exact: true })).toBeDisabled()
  await task.getByLabel('Allowed paths', { exact: true }).fill('src/')
  await task.getByLabel('AC-1', { exact: true }).fill('The value is 42')
  await task.getByLabel('Program', { exact: true }).fill('node')
  await task.getByLabel('Arguments', { exact: true }).fill('-e\nprocess.exit(0)')
  await page.screenshot({ path: test.info().outputPath('task-contract-edit-mobile.png'), fullPage: true })
  await task.getByRole('button', { name: 'Adopt task', exact: true }).click()
  await expect(task.getByRole('button', { name: 'Prepare run', exact: true })).toBeEnabled()
  expect(await page.evaluate(() => (window as any).projectFixture.adoptions)).toBe(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: test.info().outputPath('task-contract-mobile.png'), fullPage: true })
})
