import { test, expect } from '@playwright/test'

test('usage filters update both donuts, curves and model groups', async ({ page }) => {
  await page.goto('/usage.html')
  await expect(page.getByTestId('usage-total')).toHaveText('16ktokens')
  await expect(page.getByTestId('usage-cache-rate')).toHaveText('71%')
  await expect(page.locator('[data-series]')).toHaveCount(4)
  await page.getByRole('button', { name: 'Codex', exact: true }).click()
  await expect(page.getByTestId('usage-total')).toHaveText('12ktokens')
  await expect(page.getByTestId('usage-cache-rate')).toHaveText('73%')
  await expect(page.getByText('claude-sonnet-4-6')).toHaveCount(0)
  await expect(page.getByText('gpt-5.4')).toBeVisible()
  await page.locator('svg rect').nth(8).focus()
  await expect(page.locator('[aria-live="polite"]')).toContainText('08:00')
  await page.getByRole('button', { name: '本月', exact: true }).click()
  await expect(page.getByRole('button', { name: '本月', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('[data-series]')).toHaveCount(4)
  await page.getByRole('button', { name: 'OpenCode', exact: true }).click()
  await expect(page.getByTestId('usage-total')).toHaveText('0tokens')
  await expect(page.getByTestId('usage-cache-rate')).toHaveText('–')
  await expect(page.getByText('该范围内暂无带用量遥测的终端。')).toBeVisible()
})

test('usage layout fits a narrow settings pane', async ({ page }) => {
  await page.setViewportSize({ width: 480, height: 900 })
  await page.goto('/usage.html')
  await expect(page.getByTestId('usage-total')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'artifacts/usage-stats-narrow.png', fullPage: true })
  await page.setViewportSize({ width: 1000, height: 850 })
  await page.screenshot({ path: 'artifacts/usage-stats-wide.png', fullPage: true })
  await page.goto('/usage.html?theme=dark')
  await expect(page.getByTestId('usage-total')).toBeVisible()
  await page.screenshot({ path: 'artifacts/usage-stats-dark.png', fullPage: true })
})
