import { expect, test } from '@playwright/test'

test('detects global configuration with no workspace before opening Island; sources stay quiet', async ({ page }) => {
  await page.goto('/?workflowx=global')
  await expect.poll(() => page.evaluate(() => (window as any).workflowxFixture?.calls)).toEqual([null])
  await expect(page.getByTestId('harness')).toHaveAttribute('data-stage', 'collapsed')
  await expect(page.getByTestId('workflowx-monitor')).not.toBeVisible()
  await page.getByTestId('reopen-island').click()
  await page.locator('.janus-expanded-view-button[data-view="monitor"]').click()
  const monitor = page.getByTestId('workflowx-monitor')
  await expect(monitor.getByText('Detected', { exact: true })).toBeVisible()
  const summary = monitor.getByRole('button', { name: 'View WorkflowX sources' })
  await expect(summary).toHaveAttribute('aria-expanded', 'false')
  expect(await summary.evaluate(el => parseFloat(getComputedStyle(el).fontSize))).toBeLessThanOrEqual(12)
  await summary.click()
  await expect(monitor.getByText('Codex · Global · Workflow skill')).toBeVisible()
  await expect(monitor.locator('code')).toContainText('.codex/skills/orchestrateX/SKILL.md')
  await monitor.getByRole('button', { name: 'Open WorkflowX repository' }).click()
  await expect.poll(() => page.evaluate(() => (window as any).workflowxFixture.opened)).toBe(1)
  await page.screenshot({ path: test.info().outputPath('workflowx-global.png') })
  // Electron's main window minimum width is 1000px.
  await page.setViewportSize({ width: 1000, height: 640 })
  await expect(monitor.getByRole('button', { name: 'Check again' })).toBeVisible()
  await expect(monitor.getByRole('button', { name: 'Open WorkflowX repository' })).toBeVisible()
  const bounds = await monitor.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(1000)
  await page.screenshot({ path: test.info().outputPath('workflowx-compact.png') })
  await summary.focus()
  await summary.press('Escape')
  await expect(summary).toHaveAttribute('aria-expanded', 'false')
})

test('refreshes after workspace changes and window focus, without any terminal or raw exception', async ({ page }) => {
  await page.goto('/?workflowx=missing')
  await expect.poll(() => page.evaluate(() => (window as any).workflowxFixture?.calls)).toEqual(['workspace-1'])
  await page.evaluate(() => (window as any).workflowxFixture.setWorkspace('workspace-3'))
  await expect.poll(() => page.evaluate(() => (window as any).workflowxFixture.calls.at(-1))).toBe('workspace-3')
  await expect(page.getByTestId('harness')).toHaveAttribute('data-stage', 'collapsed')
  await page.getByTestId('reopen-island').click()
  await page.locator('.janus-expanded-view-button[data-view="monitor"]').click()
  const monitor = page.getByTestId('workflowx-monitor')
  await expect(monitor.getByText('Not detected', { exact: true })).toBeVisible()
  await monitor.getByRole('button', { name: 'View WorkflowX sources' }).click()
  await page.evaluate(() => { (window as any).workflowxFixture.status = 'detected'; window.dispatchEvent(new Event('focus')) })
  await expect(monitor.getByText('Detected', { exact: true })).toBeVisible()
  await page.evaluate(() => { (window as any).workflowxFixture.fail = true })
  await monitor.getByRole('button', { name: 'Check again' }).click()
  await expect(monitor.getByText('Needs confirmation', { exact: true })).toBeVisible()
  await expect(monitor).toContainText('Detection is temporarily unavailable')
  await expect(page.getByText(/Error invoking remote method|\[object Object\]/)).toHaveCount(0)
  await page.screenshot({ path: test.info().outputPath('workflowx-uncertain.png') })
})

test('periodic detection observes configuration changes while Island stays collapsed', async ({ page }) => {
  await page.clock.install()
  await page.goto('/?workflowx=missing')
  await expect.poll(() => page.evaluate(() => (window as any).workflowxFixture?.calls.length)).toBe(1)
  await page.evaluate(() => { (window as any).workflowxFixture.status = 'detected' })
  await page.clock.fastForward(30_001)
  await expect.poll(() => page.evaluate(() => (window as any).workflowxFixture.calls.length)).toBe(2)
  await expect(page.getByTestId('harness')).toHaveAttribute('data-stage', 'collapsed')
})
