import { UPDATER_RELEASES_URL } from '../../../shared/ipc/updater'
import type { ExternalCliToolId } from '../../../shared/ipc/external-cli'

export function installElectronApiFallback(): void {
  if (window.electron) return

  window.electron = {
    platform: inferPlatform(),
    workspace: {
      initialize: () => Promise.resolve({ loadState: 'no-workspace', workspaces: [], activeWorkspaceId: null }),
      list: () => Promise.resolve([]),
      load: () => Promise.reject(new Error('Electron workspace API is unavailable')),
      create: () => Promise.reject(new Error('Electron workspace API is unavailable')),
      update: () => Promise.reject(new Error('Electron workspace API is unavailable')),
      delete: () => Promise.resolve({ success: false }),
    },
    fileTree: {
      load: () => Promise.resolve([]),
      children: () => Promise.resolve([]),
      createFile: () => Promise.resolve({ success: false, error: 'Electron file tree API is unavailable' }),
      createDirectory: () => Promise.resolve({ success: false, error: 'Electron file tree API is unavailable' }),
      rename: () => Promise.resolve({ success: false, error: 'Electron file tree API is unavailable' }),
      move: () => Promise.resolve({ success: false, error: 'Electron file tree API is unavailable' }),
      delete: () => Promise.resolve({ success: false, error: 'Electron file tree API is unavailable' }),
      reveal: () => Promise.resolve({ success: false, error: 'Electron file tree API is unavailable' }),
      onChanged: () => () => {},
    },
    file: {
      read: () => Promise.resolve({ error: 'Electron file API is unavailable' }),
      save: () => Promise.resolve({ error: 'Electron file API is unavailable' }),
      readBinary: () => Promise.resolve({ error: 'Electron file API is unavailable' }),
      stat: () => Promise.resolve({ error: 'Electron file API is unavailable' }),
      sourceFiles: () => Promise.resolve({ files: [], truncated: false, error: 'Electron file API is unavailable' }),
    },
    languageService: {
      definition: () => Promise.resolve({
        target: null,
        error: { code: 'server-error', message: 'Electron language service API is unavailable' },
      }),
      installer: {
        status: () => Promise.resolve({ serviceId: 'clangd', state: 'not-installed', location: '' }),
        start: () => Promise.resolve({ serviceId: 'clangd', state: 'failed', location: '', error: 'Electron API unavailable' }),
        cancel: () => Promise.resolve({ serviceId: 'clangd', state: 'not-installed', location: '' }),
        remove: () => Promise.resolve({ serviceId: 'clangd', state: 'not-installed', location: '' }),
        onInstallerProgress: () => () => {},
      },
    },
    terminal: {
      warmup: () => Promise.resolve({ ok: true }),
      create: () => Promise.reject(new Error('Electron terminal API is unavailable')),
      replay: () => Promise.resolve({ data: '', seq: 0 }),
      kill: () => Promise.resolve({ success: true }),
      input: () => {},
      resize: () => {},
      submitLine: () => {},
      onData: () => () => {},
      onCreated: () => () => {},
      onExit: () => () => {},
      onFocus: () => () => {},
      onStatus: () => () => {},
      onTelemetry: () => () => {},
      onTurnChanges: () => () => {},
    },
    project: {
      detect: () => unavailableProjectResult(),
      detectWithDetails: () => unavailableProjectResult(),
      readConfig: () => unavailableProjectResult(),
      writeConfig: () => unavailableProjectResult(),
      createDefaultConfig: () => unavailableProjectResult(),
      validateConfig: () => unavailableProjectResult(),
      test: () => unavailableProjectResult(),
      run: () => unavailableProjectResult(),
      stop: () => unavailableProjectResult(),
      list: () => unavailableProjectResult(),
      get: () => unavailableProjectResult(),
      schemas: () => unavailableProjectResult(),
    },
    browser: {
      createSurface: unavailable,
      destroySurface: unavailable,
      popOut: unavailable,
      embed: unavailable,
      setBounds: unavailable,
      getState: () => Promise.resolve(null),
      openTab: unavailable,
      closeTab: unavailable,
      activateTab: unavailable,
      navigate: unavailable,
      goBack: unavailable,
      goForward: unavailable,
      reload: unavailable,
      onStateChanged: () => () => {},
      onAgentControlChanged: () => () => {},
    },
    knowledge: {
      contracts: () => unavailableKnowledge(),
      bootstrap: () => unavailableKnowledge(),
      observe: () => unavailableKnowledge(),
      listObservations: () => unavailableKnowledge(),
      pruneObservations: () => unavailableKnowledge(),
      autoPruneObservations: () => unavailableKnowledge(),
      resolveObservationContent: () => unavailableKnowledge(),
      retentionStats: () => unavailableKnowledge(),
      listAudit: () => unavailableKnowledge(),
      auditStats: () => unavailableKnowledge(),
      listCandidates: () => unavailableKnowledge(),
      listGraphCandidates: () => unavailableKnowledge(),
      listWikiPatchCandidates: () => unavailableKnowledge(),
      rejectCandidate: () => unavailableKnowledge(),
      applyCandidate: () => unavailableKnowledge(),
      search: () => unavailableKnowledge(),
      listTruth: () => unavailableKnowledge(),
      revokeTruth: () => unavailableKnowledge(),
      listConflicts: () => unavailableKnowledge(),
      recordFeedback: () => unavailableKnowledge(),
      feedbackSummary: () => unavailableKnowledge(),
      context: () => unavailableKnowledge(),
      diagnostics: () => unavailableKnowledge(),
      processNow: () => unavailableKnowledge(),
      processingStats: () => unavailableKnowledge(),
      externalMcpStatus: () => unavailableKnowledge(),
      registerExternalMcp: () => unavailableKnowledge(),
      userMemoryOverview: () => unavailableKnowledge(),
      getSettings: () => unavailableKnowledge(),
      updateSettings: () => unavailableKnowledge(),
    },
    janus: {
      listBlueprints: () => unavailableJanus(),
      listBlueprintSummaries: () => unavailableJanus(),
      loadBlueprint: () => unavailableJanus(),
      createBlueprint: () => unavailableJanus(),
      updateBlueprint: () => unavailableJanus(),
      deleteBlueprint: () => unavailableJanus(),
      createNode: () => unavailableJanus(),
      updateNode: () => unavailableJanus(),
      deleteNode: () => unavailableJanus(),
      replaceNodeFeatures: () => unavailableJanus(),
      addNodeFeature: () => unavailableJanus(),
      updateNodeFeature: () => unavailableJanus(),
      deleteNodeFeature: () => unavailableJanus(),
      focusNode: () => unavailableJanus(),
      bindTerminal: () => unavailableJanus(),
      analyze: () => unavailableJanus(),
      applyAnalysisPatch: () => unavailableJanus(),
      listAnalyses: () => unavailableJanus(),
      applyAnalysis: () => unavailableJanus(),
      listRequirementCandidates: () => unavailableJanus(),
      acceptRequirementCandidate: () => unavailableJanus(),
      rejectRequirementCandidate: () => unavailableJanus(),
      acceptDiscovered: () => unavailableJanus(),
      listMaintenanceTasks: () => unavailableJanus(),
      listMaintenanceAudits: () => unavailableJanus(),
      startMaintenanceTask: () => unavailableJanus(),
      applyMaintenanceChangeSet: () => unavailableJanus(),
      cancelMaintenanceTask: () => unavailableJanus(),
      completeMaintenanceTask: () => unavailableJanus(),
      dismissMaintenanceProposal: () => unavailableJanus(),
      prepareMaintenanceUndo: () => unavailableJanus(),
      applyMaintenanceUndo: () => unavailableJanus(),
      onAnalysisResult: () => () => {},
      onDiscovered: () => () => {},
      onMaintenanceTask: () => () => {},
    },
    harness: {
      taskRead: () => unavailableJanus(),
      taskAdopt: () => unavailableJanus(),
      resolve: () => unavailableJanus(),
      projectGraph: () => unavailableJanus(),
      rescan: () => unavailableJanus(),
      apply: () => unavailableJanus(),
      getBindings: () => unavailableJanus(),
      setBinding: () => unavailableJanus(),
      sharePreview: () => unavailableJanus(),
      shareExport: () => unavailableJanus(),
      shareImportPreview: () => unavailableJanus(),
      shareImportApply: () => unavailableJanus(),
      runPrepare: () => unavailableJanus(),
      runStart: () => unavailableJanus(),
      runStatus: () => unavailableJanus(),
      runList: () => unavailableJanus(),
      runCancel: () => unavailableJanus(),
      runCloseout: () => unavailableJanus(),
      runHandoff: () => unavailableJanus(),
      runHandoffRead: () => unavailableJanus(),
      runTakeover: () => unavailableJanus(),
      runThreads: () => unavailableJanus(),
      runThread: () => unavailableJanus(),
      runTranscript: () => unavailableJanus(),
      runThreadClose: () => unavailableJanus(),
      runReview: () => unavailableJanus(),
      runFinish: () => unavailableJanus(),
      runRepair: () => unavailableJanus(),
      undoPreview: () => unavailableJanus(),
      undoApply: () => unavailableJanus(),
      migratePreview: () => unavailableJanus(),
      migrateApply: () => unavailableJanus(),
      runExecute: () => unavailableJanus(),
      runPause: () => unavailableJanus(),
      runResume: () => unavailableJanus(),
      runRebaseline: () => unavailableJanus(),
      runAbort: () => unavailableJanus(),
      onChanged: () => () => {},
    },
    office: {
      detect: unavailable, listFiles: unavailable, startPreview: unavailable, stopPreview: unavailable,
      reloadPreview: unavailable, buildPrompt: unavailable,
      onFilesChanged: () => () => {}, onWatchEvicted: () => () => {},
    },
    externalCli: {
      detect: () => Promise.resolve({ toolId: 'claude' as const, installed: false, runnable: false, hint: 'Electron API is unavailable' }),
      latest: () => Promise.resolve({ toolId: 'claude' as const }),
      install: () => Promise.resolve({ toolId: 'claude' as const, success: false, error: 'Electron API is unavailable' }),
      applyProvider: () => Promise.resolve({ success: false, error: 'Electron API is unavailable' }),
      syncState: () => Promise.resolve({ claude: null }),
      rollbackProfile: () => Promise.resolve({ success: false, error: 'Electron API is unavailable' }),
      readTerminalModel: (toolId: ExternalCliToolId) => Promise.resolve({ toolId, configPath: null, exists: false, error: 'Electron API is unavailable' }),
      applyTerminalModel: () => Promise.resolve({ success: false, error: 'Electron API is unavailable' }),
      rollbackTerminal: () => Promise.resolve({ success: false, error: 'Electron API is unavailable' }),
    },
    llm: {
      getTerminalProviders: unavailable, getRuntimeStatus: unavailable, saveTerminalProvider: unavailable,
      testConnection: unavailable, removeTerminalProvider: unavailable, setTerminalDefault: unavailable,
      getTerminalDefault: unavailable, listModels: unavailable,
      getModelCatalog: unavailable, refreshModelCatalog: unavailable, getAdapters: unavailable,
      chat: unavailable, startChatStream: () => {}, abortChat: unavailable,
      steerChat: () => Promise.resolve({ accepted: false, error: 'Electron LLM API is unavailable' }),
      cancelSteerChat: () => Promise.resolve({ cancelled: false }),
      answerQuestion: () => Promise.resolve({ accepted: false, error: 'Electron LLM API is unavailable' }),
      onDelta: () => () => {}, onDone: () => () => {}, onError: () => () => {}, onRecallTrace: () => () => {},
      onToolTrace: () => () => {}, onAgentEvent: () => () => {},
    },
    agent: {
      start: unavailable, cancel: unavailable, cancelAll: unavailable, listSessions: unavailable,
      onEvent: () => () => {}, onNotification: () => () => {}, onHookEvent: () => () => {},
    },
    agentRuntime: {
      createSession: unavailable, executeTool: unavailable, cancelSession: unavailable,
      resolveApproval: () => Promise.resolve(false), getSession: () => Promise.resolve(null),
      setApprovalMode: () => Promise.resolve(null),
      queryPolicyAudit: () => Promise.resolve([]),
      executeFunctionCall: unavailable, executePlannerStep: unavailable,
      onEvent: () => () => {},
    },
    checkpoint: {
      create: unavailable, finalize: unavailable, restore: unavailable, list: unavailable,
      diff: unavailable, diffAll: unavailable, records: unavailable, delete: unavailable, clearAll: unavailable,
      onEvent: () => () => {}, onReady: () => () => {},
    },
    session: {
      list: () => Promise.resolve([]),
      get: () => Promise.resolve(null),
      continue: unavailable,
      onEvent: () => () => {},
      scanExternal: () => Promise.resolve({ scanned: 0, imported: 0, updated: 0, skipped: 0 }),
      getTranscript: () => Promise.resolve(null),
      saveLayout: () => Promise.resolve({ success: false }),
      getLayout: () => Promise.resolve(null),
      clearLayout: () => Promise.resolve({ success: false }),
    },
    worktree: {
      list: () => Promise.resolve([]),
      identity: () => Promise.resolve(null),
      avatar: () => Promise.resolve({ dataUrl: null, cached: false }),
      create: unavailable,
      cancelCreate: unavailable,
      delete: unavailable,
      status: unavailable,
      deleteBranch: unavailable,
      shipDiff: unavailable,
      shipMerge: unavailable,
      shipAbort: unavailable,
    },
    hosted: {
      detect: () => Promise.resolve(null),
      listReviews: () => Promise.resolve([]),
      checks: () => Promise.resolve([]),
      failedLogs: () => Promise.resolve([]),
      createReview: unavailable,
      mergeReview: unavailable,
      gitlabGet: unavailable,
      gitlabSave: unavailable,
      gitlabVerify: unavailable,
      gitlabClearToken: unavailable,
      listIssues: () => Promise.resolve([]),
      listComments: () => Promise.resolve([]),
      postComment: unavailable,
      setAutoMerge: unavailable,
    },
    git: {
      status: unavailable, log: unavailable, stage: unavailable, unstage: unavailable,
      commit: unavailable, push: unavailable, pull: unavailable, discard: unavailable, commitChanges: unavailable, fileBaseline: unavailable,
    },
    notificationSettings: {
      get: unavailable,
      update: unavailable,
      testFeishu: unavailable,
      getFeishuControlStatus: unavailable,
    },
    agentSettings: {      get: () => Promise.resolve({ approvalMode: 'per-action' as const, agentMaxSteps: 40, safeCompileAutoAllow: true }),
      update: (settings: { approvalMode?: unknown; agentMaxSteps?: unknown; safeCompileAutoAllow?: unknown }) => {
        const approvalMode = settings?.approvalMode === 'auto-run'
          ? ('auto-run' as const)
          : settings?.approvalMode === 'plan' ? ('plan' as const) : ('per-action' as const)
        const parsed = typeof settings?.agentMaxSteps === 'string' ? Number(settings.agentMaxSteps) : settings?.agentMaxSteps
        const agentMaxSteps = typeof parsed !== 'number' || !Number.isFinite(parsed)
          ? 40
          : Math.min(100, Math.max(1, Math.floor(parsed)))
        const safeCompileAutoAllow = settings?.safeCompileAutoAllow === undefined ? true : settings.safeCompileAutoAllow === true
        return Promise.resolve({ approvalMode, agentMaxSteps, safeCompileAutoAllow })
      },
    },
    subAgentRun: { list: unavailable, onUpdated: () => () => {}, onRemoved: () => () => {} },
    updater: {
      getState: () => Promise.resolve({
        phase: 'unsupported' as const,
        supported: false,
        unsupportedReason: 'dev-mode' as const,
        currentVersion: '',
        availableVersion: null,
        downloadPercent: null,
        releaseNotes: null,
        error: null,
      }),
      check: () => Promise.resolve({
        phase: 'unsupported' as const,
        supported: false,
        unsupportedReason: 'dev-mode' as const,
        currentVersion: '',
        availableVersion: null,
        downloadPercent: null,
        releaseNotes: null,
        error: null,
      }),
      install: () => Promise.resolve({ ok: false, error: 'unsupported' }),
      onEvent: () => () => {},
      getSettings: () => Promise.resolve({ autoCheck: true }),
      updateSettings: (settings: { autoCheck?: unknown }) => Promise.resolve({
        autoCheck: settings?.autoCheck === undefined ? true : settings.autoCheck === true,
      }),
      openReleases: () => {
        window.open(UPDATER_RELEASES_URL, '_blank', 'noopener')
        return Promise.resolve()
      },
    },
    team: {
      register: unavailable, login: unavailable, logout: unavailable, refresh: unavailable,
      me: unavailable, listTenants: unavailable, createTenant: unavailable, switchTenant: unavailable,
      inviteMember: unavailable, acceptInvite: unavailable, listMembers: unavailable,
      listProjects: unavailable, setRole: unavailable, setMemberStatus: unavailable,
    },
    remote: {
      issueCode: unavailable, redeemCode: unavailable, listTerminals: unavailable,
      tail: unavailable, execute: unavailable, issueActionToken: unavailable,
      listTrusted: unavailable, revokeDevice: unavailable,
    },
    peer: {
      hostStatus: unavailable, startHost: unavailable, stopHost: unavailable,
      discover: unavailable, pair: unavailable, peers: unavailable,
      listTerminals: unavailable, tail: unavailable, execute: unavailable,
      disconnect: unavailable, forget: unavailable,
    },
    roundtable: { start: unavailable, advance: unavailable, end: unavailable, getState: unavailable, restore: unavailable, export: unavailable, buildBundle: unavailable, applyBundle: unavailable, onEvent: () => () => {} },
    dialog: { openDirectory: unavailable, saveFile: unavailable, showMessageBox: unavailable },
    window: {
      minimize: unavailable,
      maximize: unavailable,
      close: unavailable,
      openEditor: unavailable,
      editorReady: () => {},
      embedEditor: unavailable,
      setAlwaysOnTop: unavailable,
      onEditorEmbedded: () => () => {},
      onEditorRefresh: () => () => {},
    },
    system: { getDefaultShell: unavailable, getPlatform: unavailable, openVSCode: unavailable, getRuntimeTelemetry: unavailable, getLanguage: () => Promise.resolve(null), setLanguage: unavailable, onPrepareQuit: () => () => {} },
    desktopToast: { ready: () => {}, action: () => {}, onShow: () => () => {}, onHide: () => () => {} },
    janusPersona: '',
  }
}

function unavailableProjectResult(): Promise<{ success: false; error: string }> {
  return Promise.resolve({ success: false, error: 'Electron project API is unavailable' })
}

function unavailableKnowledge(): Promise<never> {
  return Promise.reject(new Error('Electron knowledge API is unavailable'))
}

function unavailableJanus(): Promise<never> {
  return Promise.reject(new Error('Electron Janus API is unavailable'))
}

function unavailable(): Promise<never> {
  return Promise.reject(new Error('Electron API is unavailable'))
}

function inferPlatform(): NodeJS.Platform {
  const platform = navigator.platform.toLowerCase()
  if (platform.includes('win')) return 'win32'
  if (platform.includes('mac')) return 'darwin'
  if (platform.includes('linux')) return 'linux'
  return 'win32'
}
