import type {
  KnowledgeSchemaContract,
  KnowledgeStorageLayout,
  KnowledgeWritePolicy,
  KnowledgeContractsSnapshot,
} from '../../shared/knowledge'
import { KNOWLEDGE_SCHEMA_VERSION } from './constants'

export const KNOWLEDGE_STORAGE_LAYOUT: KnowledgeStorageLayout = {
  version: KNOWLEDGE_SCHEMA_VERSION,
  rootDirName: 'global',
  directories: [
    { key: 'meta', relativePath: 'meta', purpose: 'Schema, storage, and write-policy contracts.' },
    { key: 'observations', relativePath: 'observations', purpose: 'Append-only raw observation source of truth.' },
    { key: 'observations-active', relativePath: 'observations/active', purpose: 'Monthly sharded observation files (YYYY-MM.jsonl); new records are written here.' },
    { key: 'observations-archive', relativePath: 'observations/archive', purpose: 'Gzipped archived monthly shards; still aggregated for reads.' },
    { key: 'blobs', relativePath: 'blobs', purpose: 'Compressed large-content blobs for long observations.' },
    { key: 'facts', relativePath: 'facts', purpose: 'Derived facts and fact candidates.' },
    { key: 'wiki', relativePath: 'wiki', purpose: 'Human-readable knowledge pages and patch drafts.' },
    { key: 'graph', relativePath: 'graph', purpose: 'Entity relations and graph candidates.' },
    { key: 'audit', relativePath: 'audit', purpose: 'Append-only audit trail for every mutation.' },
    { key: 'indexes', relativePath: 'indexes', purpose: 'BM25 and graph side indexes, rebuildable from source layers.' },
  ],
  files: [
    { key: 'schema', relativePath: 'meta/schema.json', format: 'json', purpose: 'Knowledge data contract snapshot.' },
    { key: 'storage-layout', relativePath: 'meta/storage-layout.json', format: 'json', purpose: 'Filesystem layout contract snapshot.' },
    { key: 'write-policy', relativePath: 'meta/write-policy.json', format: 'json', purpose: 'Write and review rules snapshot.' },
    { key: 'readme', relativePath: 'README.md', format: 'markdown', purpose: 'Human-readable purpose and maintenance guide.' },
    { key: 'observations', relativePath: 'observations/observations.jsonl', format: 'jsonl', purpose: 'Legacy flat observation log; superseded by observations/active/*.jsonl for new writes but kept for backward-compat reads.' },
    { key: 'fact-candidates', relativePath: 'facts/candidates.jsonl', format: 'jsonl', purpose: 'Candidate facts awaiting review.' },
    { key: 'facts', relativePath: 'facts/facts.jsonl', format: 'jsonl', purpose: 'Accepted active facts, versioned.' },
    { key: 'wiki-pages-index', relativePath: 'wiki/pages-index.json', format: 'json', purpose: 'Wiki page registry and metadata.' },
    { key: 'graph-candidates', relativePath: 'graph/candidates.jsonl', format: 'jsonl', purpose: 'Candidate graph edges awaiting review.' },
    { key: 'graph-edges', relativePath: 'graph/edges.jsonl', format: 'jsonl', purpose: 'Accepted graph edges.' },
    { key: 'audit', relativePath: 'audit/audit.jsonl', format: 'jsonl', purpose: 'Append-only audit events for all changes.' },
    { key: 'bm25-index', relativePath: 'indexes/bm25.json', format: 'json', purpose: 'Rebuildable BM25 metadata and term dictionary.' },
    { key: 'graph-snapshot', relativePath: 'indexes/graph-snapshot.json', format: 'json', purpose: 'Graph side-index snapshot for fast loading.' },
  ],
}

export const KNOWLEDGE_WRITE_POLICY: KnowledgeWritePolicy = {
  version: KNOWLEDGE_SCHEMA_VERSION,
  principles: [
    'Observation is the immutable source-of-truth layer.',
    'Knowledge storage is global; workspace fields are provenance, filters, and audit anchors.',
    'Derived knowledge must remain rebuildable from observations plus audit history.',
    'LLM-generated outputs may only enter candidate collections until reviewed.',
    'Every accepted, rejected, superseded, or applied change must emit an audit event.',
    'Code truth beats stale memory when the two conflict.',
  ],
  directWriteCollections: [
    'observations/observations.jsonl',
    'observations/active/*.jsonl',
    'observations/archive/*.jsonl.gz',
    'blobs/*.txt.gz',
    'facts/facts.jsonl',
    'graph/edges.jsonl',
    'wiki/*.md',
    'audit/audit.jsonl',
    'indexes/*.json',
  ],
  candidateOnlyCollections: [
    'facts/candidates.jsonl',
    'graph/candidates.jsonl',
    'wiki patch proposals',
  ],
  auditRequiredActions: [
    'capture',
    'extract',
    'candidate_proposed',
    'candidate_approved',
    'candidate_rejected',
    'candidate_applied',
    'wiki_updated',
    'fact_superseded',
    'reindex',
    'observation_pruned',
    'observation_auto_pruned',
    'observation_archived',
    'observation_compacted',
  ],
  requiredProvenanceFields: [
    'workspaceId',
    'workspaceName',
    'workspacePath',
    'source',
    'sourceObservationIds',
    'fileRefs',
    'actor',
    'createdAt',
  ],
}

export const KNOWLEDGE_SCHEMA_CONTRACT: KnowledgeSchemaContract = {
  version: KNOWLEDGE_SCHEMA_VERSION,
  status: 'implemented',
  entities: {
    observation: [
      'id',
      'workspaceId',
      'workspaceName',
      'workspacePath',
      'source',
      'type',
      'content',
      'summary',
      'fileRefs',
      'tags',
      'visibility',
      'actor',
      'createdAt',
      'correlationId',
      'metadata',
      'retentionClass',
      'retentionReason',
      'contentHash',
      'contentLength',
      'contentPreview',
      'blobRef',
      'originalLength',
      'truncated',
      'compactionStatus',
      'compactedAt',
    ],
    memoryFact: [
      'id',
      'content',
      'concepts',
      'files',
      'tags',
      'confidence',
      'version',
      'supersedes',
      'status',
      'provenance',
    ],
    wikiPage: [
      'slug',
      'title',
      'markdown',
      'tags',
      'status',
      'sourceFactIds',
      'updatedAt',
      'version',
      'workspaceId',
    ],
    graphEdge: [
      'id',
      'from',
      'to',
      'type',
      'confidence',
      'sourceFactIds',
      'workspaceId',
      'createdAt',
    ],
    auditEvent: [
      'id',
      'action',
      'targetType',
      'targetId',
      'before',
      'after',
      'provenance',
    ],
    candidateWikiPatch: [
      'id',
      'type',
      'status',
      'pageSlug',
      'title',
      'patchMarkdown',
      'rationale',
      'confidence',
      'provenance',
      'reviewNotes',
    ],
  },
  rules: [
    'Observation records are append-only and may not be mutated in place.',
    'Memory facts are versioned; replacement uses supersedes instead of destructive overwrite.',
    'Wiki pages are human-readable outputs backed by fact provenance.',
    'Graph edges remain derived and rebuildable from accepted facts plus audit history.',
    'LLM output can never bypass candidate review queues.',
  ],
}

export function getKnowledgeContractsSnapshot(): KnowledgeContractsSnapshot {
  return {
    schema: KNOWLEDGE_SCHEMA_CONTRACT,
    storage: KNOWLEDGE_STORAGE_LAYOUT,
    writePolicy: KNOWLEDGE_WRITE_POLICY,
  }
}
