/**
 * 主题 CSS 代码生成入口（被 scripts/generate-theme-css.mjs 打包执行）。
 * 输出 themes.generated.css：:root（默认主题）+ 各主题 [data-theme] 块 + ::selection。
 * 组件皮肤覆盖（如灵动岛、选择器）不在此列，手写 CSS 保留。
 */
import { DEFAULT_APP_THEME } from '../ipc/theme'
import { listThemeDefinitions } from './registry'

export function renderThemeCss(): string {
  const definitions = listThemeDefinitions()
  const defaultDefinition = definitions.find((d) => d.id === DEFAULT_APP_THEME) ?? definitions[0]
  const lines: string[] = [
    '/* AUTO-GENERATED by scripts/generate-theme-css.mjs — do not edit by hand. */',
    '/* Source of truth: src/shared/theme/definition.ts */',
    '',
  ]
  if (defaultDefinition.notes) {
    lines.push(`/* Default (${defaultDefinition.id}): ${defaultDefinition.notes} */`)
  }
  lines.push(':root {')
  for (const [key, value] of Object.entries(defaultDefinition.tokens)) {
    lines.push(`  --${key}: ${value};`)
  }
  lines.push('}')
  lines.push('')
  lines.push(`:root::selection {`)
  lines.push(`  background: ${defaultDefinition.selection};`)
  lines.push('}')
  for (const definition of definitions) {
    if (definition.id === defaultDefinition.id) continue
    lines.push('')
    if (definition.notes) {
      lines.push(`/* ${definition.id}: ${definition.notes} */`)
    }
    lines.push(`[data-theme='${definition.id}'] {`)
    for (const [key, value] of Object.entries(definition.tokens)) {
      lines.push(`  --${key}: ${value};`)
    }
    lines.push('}')
    lines.push('')
    lines.push(`[data-theme='${definition.id}'] ::selection {`)
    lines.push(`  background: ${definition.selection};`)
    lines.push('}')
  }
  lines.push('')
  return lines.join('\n')
}
